(()=>{
  "use strict";
  // Set only after code review, deployment and verification of the on-chain config.
  const REGISTRY=null;
  const RESTS=["https://juno-api.polkachu.com","https://juno-api.lavenderfive.com"];
  const search=document.querySelector("#names-search"),result=document.querySelector("#names-result");
  function validName(value){if(!value.endsWith(".neta"))return false;const label=value.slice(0,-5);return /^(?=.{5,32}$)[a-z0-9]+(?:-[a-z0-9]+)*$/.test(label)&&!["admin","neta","relay","support","treasury","governance"].includes(label)}
  function validAddress(value){return /^juno1[023456789acdefghjklmnpqrstuvwxyz]{38,90}$/.test(value)}
  async function query(message){if(!REGISTRY)throw new Error("The NETA Names registry is awaiting deployment.");const encoded=btoa(JSON.stringify(message));for(const base of RESTS){try{const response=await fetch(`${base}/cosmwasm/wasm/v1/contract/${REGISTRY}/smart/${encodeURIComponent(encoded)}`,{cache:"no-store"});if(response.ok){const body=await response.json();return body.data??body}}catch{}}throw new Error("The Juno registry could not be reached. Try again later.")}
  async function resolve(value){const normalized=value.trim().toLowerCase();if(validName(normalized))return query({resolve:{name:normalized}});if(validAddress(normalized))return query({name_of:{address:normalized}});throw new Error("Enter a valid .neta name or Juno address.")}
  window.NetaNames={resolve,validName,validAddress,active:!!REGISTRY};
  search?.addEventListener("submit",async event=>{event.preventDefault();const value=search.querySelector("input").value.trim();result.textContent="LOOKING UP ON JUNO…";try{const found=await resolve(value);if("expires_at" in found){result.textContent=found.address?`${found.name} → ${found.address} · expires ${new Date(found.expires_at*1000).toLocaleDateString()}`:found.in_grace?`${found.name} is expired and reserved for renewal.`:`${found.name} is available or unregistered.`}else result.textContent=found.name?`${found.address} → ${found.name}`:"No active .neta name is registered for this address."}catch(error){result.textContent=error.message}});
  const DAO_TREASURY="juno1c5v6jkmre5xa9vf9aas6yxewc7aqmjy0rlkkyk4d88pnwuhclyhsrhhns6";
  const INITIAL_FEE="5000000",PENDING_KEY="neta-names-pending:v1";
  const register=document.querySelector("#names-register"),action=document.querySelector("#names-register-action"),registrationStatus=document.querySelector("#names-register-status"),restart=document.querySelector("#names-restart");
  const pending=()=>{try{return JSON.parse(sessionStorage.getItem(PENDING_KEY))}catch{return null}};
  function showRegistration(){if(!REGISTRY)return;const saved=pending();if(saved)register.querySelector("input").value=saved.name;restart.hidden=!saved;action.disabled=false;action.textContent=saved?"COMPLETE REGISTRATION →":"REGISTER · 5 NETA →";registrationStatus.textContent=saved?`Commitment saved for ${saved.name}. Complete the registration from the same wallet within 100 Juno blocks.`:"Connect Keplr to commit your name, then return to complete the 5 NETA payment after one block."}
  async function signer(){if(!window.keplr)throw new Error("Keplr is required.");await window.keplr.enable("juno-1");const base=window.keplr.getOfflineSigner?.("juno-1");if(!base)throw new Error("Keplr signer unavailable.");const account=(await base.getAccounts())[0];if(!validAddress(account?.address||""))throw new Error("Connect a Juno wallet.");const wrapped={getAccounts:()=>base.getAccounts(),signDirect:(a,d)=>window.keplr.signDirect("juno-1",a,d,{preferNoSetFee:true}),signAmino:(a,d)=>window.keplr.signAmino("juno-1",a,d,{preferNoSetFee:true})};for(const rpc of ["https://juno-rpc.polkachu.com","https://rpc-juno.whispernode.com"])try{return {address:account.address,client:await NetaSocialsTestnet.connect(rpc,wrapped)}}catch{}throw new Error("Could not connect to Juno RPC.")}
  async function digest(value){const bytes=new TextEncoder().encode(value);return [...new Uint8Array(await crypto.subtle.digest("SHA-256",bytes))].map(b=>b.toString(16).padStart(2,"0")).join("")}
  function base64(value){return btoa(String.fromCharCode(...new TextEncoder().encode(JSON.stringify(value))))}
  async function checkedConfig(){const config=await query({config:{}});if(config.treasury!==DAO_TREASURY)throw new Error("Registry treasury does not match NETA DAO. Payment blocked.");const info=await (async()=>{for(const base of RESTS)try{const response=await fetch(`${base}/cosmwasm/wasm/v1/contract/${config.token}/smart/${encodeURIComponent(base64({token_info:{}}))}`,{cache:"no-store"});if(response.ok){const body=await response.json();return body.data??body}}catch{}throw new Error("Could not verify the NETA token.")})();if(info.symbol!=="NETA"||info.decimals!==6)throw new Error("Token metadata does not match NETA (6 decimals).");return config}
  restart?.addEventListener("click",()=>{sessionStorage.removeItem(PENDING_KEY);register.reset();registrationStatus.textContent="Commitment cleared in this browser. An earlier on-chain commitment may remain until it expires.";showRegistration()});
  register?.addEventListener("submit",async event=>{event.preventDefault();if(!REGISTRY)return;action.disabled=true;try{const name=register.querySelector("input").value.trim().toLowerCase();if(!validName(name))throw new Error("Use 5–32 lowercase letters, digits or interior hyphens before .neta.");registrationStatus.textContent="Verifying the registry and wallet…";const config=await checkedConfig(),{address,client}=await signer();let saved=pending();if(saved&&saved.name!==name)throw new Error(`Finish ${saved.name} or clear this browser session before choosing another name.`);if(saved&&saved.address!==address)throw new Error(`Reconnect the Juno wallet that committed ${saved.name}.`);if(!saved){const available=await query({resolve:{name}});if(available.address||available.in_grace)throw new Error("This name is unavailable.");const owned=await query({name_of:{address}});if(owned.name)throw new Error(`This wallet already owns ${owned.name}.`);const salt=[...crypto.getRandomValues(new Uint8Array(32))].map(b=>b.toString(16).padStart(2,"0")).join("");const hash=await digest(`neta-names-v1:${name.slice(0,-5)}:${address}:${salt}`);registrationStatus.textContent="Confirm the name commitment in Keplr…";await NetaSocialsTestnet.execute(client,address,REGISTRY,{commit:{hash}},`Commit ${name}`);saved={name,address,salt,hash};sessionStorage.setItem(PENDING_KEY,JSON.stringify(saved));registrationStatus.textContent="Commit confirmed. Wait at least one Juno block, then select COMPLETE REGISTRATION.";return}
    const block=await query({commitment:{address,hash:saved.hash}});if(block===null)throw new Error("Commitment not found. It may have expired; restart in a new browser session.");const latest=await query({resolve:{name}});if(latest.address||latest.in_grace)throw new Error("The name is no longer available.");await checkedConfig();registrationStatus.textContent="Confirm the exact 5 NETA registration in Keplr…";await NetaSocialsTestnet.execute(client,address,config.token,{send:{contract:REGISTRY,amount:INITIAL_FEE,msg:base64({register:{name,salt:saved.salt}})}},`Register ${name} for 5 NETA`);sessionStorage.removeItem(PENDING_KEY);restart.hidden=true;const resolved=await query({resolve:{name}});registrationStatus.textContent=resolved.address===address?`${name} now resolves to ${address}.`:`Registration broadcast. Verify ${name} on Juno before relying on it.`;
  }catch(error){registrationStatus.textContent=error?.message||String(error)}finally{action.disabled=false;action.textContent=pending()?"COMPLETE REGISTRATION →":"REGISTER · 5 NETA →"}});
  const renew=document.querySelector("#names-renew"),renewStatus=document.querySelector("#names-renew-status");
  if(REGISTRY&&renew){renew.disabled=false;renew.textContent="RENEW YOUR NAME →"}
  renew?.addEventListener("click",async()=>{if(!REGISTRY)return;renew.disabled=true;try{renewStatus.textContent="Checking your name and current renewal quote…";const {address,client}=await signer(),owned=await query({name_of:{address}});let name=owned.name;if(!name){const typed=register.querySelector("input").value.trim().toLowerCase();if(!validName(typed))throw new Error("Enter your .neta name above to renew an expired name.");name=typed}const record=await query({resolve:{name}});if(record.address&&record.address!==address)throw new Error("This name belongs to another wallet.");if(!record.expires_at)throw new Error("This name is not registered.");const now=Math.floor(Date.now()/1000);if(now>=record.expires_at+30*24*60*60)throw new Error("The 30-day renewal grace period has ended.");const config=await checkedConfig(),amount=config.renewal_fee;if(!/^[1-9][0-9]*$/.test(String(amount)))throw new Error("Invalid on-chain renewal quote.");const display=(Number(amount)/1e6).toLocaleString(undefined,{maximumFractionDigits:6});renewStatus.textContent=`Keplr will request ${display} NETA for one year. Review the amount and NETA DAO recipient before signing.`;const current=await checkedConfig();if(current.renewal_fee!==amount)throw new Error("The renewal price changed. Review the new quote and retry.");await NetaSocialsTestnet.execute(client,address,config.token,{send:{contract:REGISTRY,amount:String(amount),msg:base64({renew:{name}})}},`Renew ${name} · ${display} NETA`);const updated=await query({resolve:{name}});renewStatus.textContent=updated.expires_at>record.expires_at?`${name} renewed until ${new Date(updated.expires_at*1000).toLocaleDateString()}.`:`Renewal broadcast. Verify the new expiry on Juno.`}catch(error){renewStatus.textContent=error?.message||String(error)}finally{renew.disabled=false}});
  showRegistration();
  const recipient=document.querySelector("#relay-recipient");
  if(recipient){const note=document.createElement("p");note.id="relay-recipient-resolution";note.className="names-resolution";note.setAttribute("role","status");recipient.after(note);let sequence=0;recipient.addEventListener("change",async()=>{const value=recipient.value.trim(),current=++sequence;note.textContent="";if(!value.endsWith(".neta"))return;try{const found=await resolve(value);if(current===sequence)note.textContent=found.address?`RESOLVES TO ${found.address} · verify this address before future sending`:"No active Juno address found for this name."}catch(error){if(current===sequence)note.textContent=error.message}})}
})();
