(()=>{
  "use strict";
  const MAINNET_RESTS=["https://juno-api.polkachu.com","https://juno-api.lavenderfive.com"];
  const OPS_MODULE="juno1m9skms04ymmhsyc2q9cguja47d07mljsfnvm8f584dc645urxvjsjc9ep0";
  const FAVORITES_KEY="neta-relay-favorites:v1",STATE_KEY="neta-relay-state:v1",EVENTS_KEY="neta-relay-notifications:v1";
  const DEFAULT_FAVORITES=["neta-operations","juno"];
  const feed=document.querySelector("#relay-feed");
  if(!feed)return;
  const status=document.querySelector("#relay-status"),badge=document.querySelector("#relay-unread-badge"),count=document.querySelector("#relay-unread-count"),markRead=document.querySelector("#relay-mark-read");
  let filter="all",favorites=read(FAVORITES_KEY,DEFAULT_FAVORITES),previous=read(STATE_KEY,null),events=read(EVENTS_KEY,[]),loading=false;

  function read(key,fallback){try{const value=JSON.parse(localStorage.getItem(key));return value??fallback}catch{return fallback}}
  function write(key,value){try{localStorage.setItem(key,JSON.stringify(value))}catch{}}
  function encode(query){return encodeURIComponent(btoa(JSON.stringify(query)))}
  function compact(value){return String(value??"").replace(/\s+/g," ").trim()}
  function digest(item){return JSON.stringify([item.title,item.status,item.revision,item.summary])}
  function timeout(promise,ms=12000){return Promise.race([promise,new Promise((_,reject)=>setTimeout(()=>reject(new Error("request timed out")),ms))])}
  async function get(path){const failures=[];for(const base of MAINNET_RESTS)try{const response=await timeout(fetch(base+path,{cache:"no-store"}));if(response.ok)return response.json();failures.push(`HTTP ${response.status}`)}catch(error){failures.push(error.message)}throw new Error(failures.join(" · "))}
  async function smart(contract,query){const result=await get(`/cosmwasm/wasm/v1/contract/${contract}/smart/${encode(query)}`);return result.data||result}
  function normalizeOps(proposal){const id=String(proposal.id??proposal.proposal_id??"");return{key:`neta-operations:${id}`,dao:"neta-operations",daoLabel:"NETA OPERATIONS",id,title:compact(proposal.title||proposal.proposal?.title)||`Operations proposal #${id}`,status:compact(proposal.status||proposal.proposal?.status||"UNKNOWN").toUpperCase(),revision:Number(proposal.current_revision||proposal.latest_version||proposal.revision||0),summary:compact(proposal.description||proposal.summary||proposal.proposal?.description),kind:"governance"}}
  function normalizeJuno(proposal){const id=String(proposal.id||"");const message=proposal.messages?.[0]||{};return{key:`juno:${id}`,dao:"juno",daoLabel:"JUNO GOVERNANCE",id,title:compact(proposal.title)||compact(message.content?.title)||`Juno proposal #${id}`,status:compact(proposal.status||"UNKNOWN").replace(/^PROPOSAL_STATUS_/,"").replaceAll("_"," "),revision:0,summary:compact(proposal.summary||proposal.metadata||message.content?.description),kind:"governance"}}
  async function loadOperations(){const items=[];let startBefore=null;for(let page=0;page<4;page++){const data=await smart(OPS_MODULE,{reverse_proposals:{start_before:startBefore,limit:30}}),batch=data.proposals||[];items.push(...batch.map(normalizeOps));if(batch.length<30)break;startBefore=batch.at(-1)?.id}return items}
  async function loadJuno(){const data=await get("/cosmos/gov/v1/proposals?pagination.reverse=true&pagination.limit=100");return(data.proposals||[]).map(normalizeJuno)}
  function eventFor(item,type,detail){return{id:`${item.key}:${type}:${Date.now()}:${Math.random().toString(36).slice(2,7)}`,proposalKey:item.key,dao:item.dao,daoLabel:item.daoLabel,proposalId:item.id,title:item.title,type,detail,kind:item.kind,createdAt:new Date().toISOString(),read:false}}
  function compare(items){const next={updatedAt:new Date().toISOString(),items:{...(previous?.items||{})}};items.forEach(item=>{next.items[item.key]={...item,digest:digest(item)}});if(previous?.items){for(const item of items){const old=previous.items[item.key];if(!old){events.unshift(eventFor(item,"NEW PROPOSAL",item.status));continue}if(old.status!==item.status)events.unshift(eventFor(item,"STATUS CHANGED",`${old.status} → ${item.status}`));else if(old.digest!==digest(item))events.unshift(eventFor(item,item.revision>Number(old.revision||0)?"NEW REVISION":"PROPOSAL CHANGED",item.revision?`REVISION ${item.revision}`:"CONTENT UPDATED"))}}else{events=items.slice(0,8).map(item=>({...eventFor(item,"CURRENT PROPOSAL",item.status),read:true}))}previous=next;events=events.slice(0,200);write(STATE_KEY,previous);write(EVENTS_KEY,events)}
  function visibleEvents(){return events.filter(item=>favorites.includes(item.dao)&&(filter==="all"||filter==="unread"&&!item.read||filter===item.kind))}
  function render(){document.querySelectorAll("[data-relay-dao]").forEach(button=>{const followed=favorites.includes(button.dataset.relayDao);button.setAttribute("aria-pressed",String(followed));button.querySelector("i").textContent=followed?"★":"☆"});const unread=events.filter(item=>favorites.includes(item.dao)&&!item.read).length;badge.hidden=unread===0;badge.textContent=String(unread);count.hidden=unread===0;count.textContent=String(unread);markRead.disabled=unread===0;feed.replaceChildren();const selected=visibleEvents();if(!selected.length){const empty=document.createElement("p");empty.className="relay-empty";empty.textContent=filter==="messages"?"ENCRYPTED MESSAGING IS NOT ACTIVE YET":"NO UPDATES IN THIS VIEW";feed.append(empty);return}selected.forEach(item=>{const row=document.createElement("button");row.type="button";row.className=`relay-event${item.read?"":" unread"}`;const dot=document.createElement("i");dot.className="relay-event-dot";dot.setAttribute("aria-hidden","true");const main=document.createElement("div");main.className="relay-event-main";const meta=document.createElement("small");meta.textContent=`${item.daoLabel} · ${item.type}`;const title=document.createElement("strong");title.textContent=item.title;const detail=document.createElement("span");detail.textContent=`#${item.proposalId} · ${item.detail}`;const time=document.createElement("time");time.dateTime=item.createdAt;time.textContent=new Date(item.createdAt).toLocaleDateString([], {day:"2-digit",month:"short",year:"numeric"});main.append(meta,title,detail,time);row.setAttribute("aria-label",`${item.daoLabel}: ${item.title}. ${item.type}. Open proposal`);const action=document.createElement("span");action.className="relay-event-action";action.textContent="OPEN →";row.addEventListener("click",()=>{item.read=true;write(EVENTS_KEY,events);render();document.querySelector('[data-workspace-view="governance"]')?.click();window.dispatchEvent(new CustomEvent("neta:relay-open",{detail:{dao:item.dao,proposalId:item.proposalId}}))});row.append(dot,main,action);feed.append(row)})}
  async function refresh(){if(loading)return;loading=true;status.textContent="CHECKING GOVERNANCE SOURCES…";const jobs=[];if(favorites.includes("neta-operations"))jobs.push(loadOperations());if(favorites.includes("juno"))jobs.push(loadJuno());try{const settled=await Promise.allSettled(jobs),items=settled.filter(result=>result.status==="fulfilled").flatMap(result=>result.value);if(!items.length&&jobs.length)throw new Error("all sources unavailable");compare(items);const failed=settled.filter(result=>result.status==="rejected").length;status.textContent=`${items.length} PROPOSALS CHECKED${failed?` · ${failed} SOURCE UNAVAILABLE`:""} · ${new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}`;render()}catch(error){status.textContent=`RELAY UPDATE FAILED · ${compact(error.message).toUpperCase()}`;render()}finally{loading=false}}
  document.querySelectorAll("[data-relay-dao]").forEach(button=>button.addEventListener("click",()=>{const id=button.dataset.relayDao;favorites=favorites.includes(id)?favorites.filter(item=>item!==id):[...favorites,id];write(FAVORITES_KEY,favorites);render();refresh()}));
  document.querySelectorAll("[data-relay-filter]").forEach(button=>button.addEventListener("click",()=>{filter=button.dataset.relayFilter;document.querySelectorAll("[data-relay-filter]").forEach(item=>{item.classList.toggle("active",item===button);item.setAttribute("aria-pressed",String(item===button))});render()}));
  markRead.addEventListener("click",()=>{events.forEach(item=>{if(favorites.includes(item.dao))item.read=true});write(EVENTS_KEY,events);render()});
  const composer=document.querySelector("#relay-composer"),newMessage=document.querySelector("#relay-new-message"),recipient=document.querySelector("#relay-recipient"),message=document.querySelector("#relay-message");
  function closeComposer(){composer.hidden=true;newMessage.setAttribute("aria-expanded","false");composer.reset()}
  newMessage.addEventListener("click",()=>{const opening=composer.hidden;composer.hidden=!opening;newMessage.setAttribute("aria-expanded",String(opening));if(opening)recipient.focus()});
  document.querySelector("#relay-discard-message").addEventListener("click",()=>{closeComposer();status.textContent="NEW MESSAGE DISCARDED"});
  composer.addEventListener("submit",event=>event.preventDefault());
  recipient.addEventListener("input",()=>{const target=document.querySelector("#relay-recipient-resolution");if(target)target.textContent=""});
  render();refresh();setInterval(refresh,60000);document.addEventListener("visibilitychange",()=>{if(!document.hidden)refresh()});
})();
