import assert from 'node:assert/strict';
import http from 'node:http';
import { readFile } from 'node:fs/promises';
import { chromium } from 'playwright';

const root = new URL('./node_modules/@wireapp/core-crypto/dist/browser/', import.meta.url);
const paths = {
  '/corecrypto.js': new URL('corecrypto.js', root),
  '/index_bg.wasm': new URL('autogenerated/wasm-bindgen/index_bg.wasm', root),
};
const server = http.createServer(async (request, response) => {
  if (request.url === '/') {
    response.writeHead(200, {
      'content-type': 'text/html',
      'content-security-policy': "default-src 'none'; script-src 'self' 'wasm-unsafe-eval'; connect-src 'self'; worker-src 'self'; style-src 'none'; object-src 'none'; base-uri 'none'",
    });
    response.end('<!doctype html><title>RELAY browser crypto test</title>');
    return;
  }
  if (!Object.hasOwn(paths, request.url)) {
    response.writeHead(404).end();
    return;
  }
  try {
    response.writeHead(200, { 'content-type': request.url.endsWith('.wasm') ? 'application/wasm' : 'text/javascript' });
    response.end(await readFile(paths[request.url]));
  } catch (error) {
    response.writeHead(500).end(error.message);
  }
});
await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
const origin = `http://127.0.0.1:${server.address().port}`;
let browser;

async function startClient(page, name) {
  await page.goto(origin);
  await page.evaluate(async name => {
    const crypto = await import('/corecrypto.js');
    await crypto.initWasmModule('/index_bg.wasm');
    const key = new crypto.DatabaseKey(new Uint8Array(32).fill(name === 'alice' ? 11 : 22));
    const db = await crypto.Database.open(`${name}.db`, key);
    const client = crypto.CoreCrypto.new(db);
    await client.transaction(ctx => ctx.proteusInit());
    window.relayClient = client;
  }, name);
}

try {
  browser = await chromium.launch({ headless: true });
  // Contexts have separate storage, even though they visit the same origin.
  const aliceContext = await browser.newContext();
  const bobContext = await browser.newContext();
  let alice = await aliceContext.newPage();
  let bob = await bobContext.newPage();
  await startClient(alice, 'alice');
  await startClient(bob, 'bob');

  const prekey = await bob.evaluate(async () => Array.from(await window.relayClient.transaction(ctx => ctx.proteusNewPrekey(1))));
  const initial = await alice.evaluate(async prekey => Array.from(await window.relayClient.transaction(async ctx => {
    await ctx.proteusSessionFromPrekey('bob', new Uint8Array(prekey));
    return ctx.proteusEncrypt('bob', new TextEncoder().encode('hello from Alice'));
  })), prekey);
  assert.ok(!new TextDecoder().decode(new Uint8Array(initial)).includes('hello from Alice'), 'ciphertext exposed plaintext');

  // A tab restart must restore the persisted ratchet and prekey before delivery.
  await bob.close();
  bob = await bobContext.newPage();
  await startClient(bob, 'bob');
  const received = await bob.evaluate(async envelope => new TextDecoder().decode(await window.relayClient.transaction(ctx => ctx.proteusDecryptSafe('alice', new Uint8Array(envelope)))), initial);
  assert.equal(received, 'hello from Alice');

  const reply = await bob.evaluate(async () => Array.from(await window.relayClient.transaction(ctx => ctx.proteusEncrypt('alice', new TextEncoder().encode('hello from Bob')))));
  const response = await alice.evaluate(async envelope => new TextDecoder().decode(await window.relayClient.transaction(ctx => ctx.proteusDecryptSafe('bob', new Uint8Array(envelope)))), reply);
  assert.equal(response, 'hello from Bob');

  const older = await alice.evaluate(async () => Array.from(await window.relayClient.transaction(ctx => ctx.proteusEncrypt('bob', new TextEncoder().encode('older')))));
  const newer = await alice.evaluate(async () => Array.from(await window.relayClient.transaction(ctx => ctx.proteusEncrypt('bob', new TextEncoder().encode('newer')))));
  async function receive(envelope) {
    return bob.evaluate(async bytes => new TextDecoder().decode(await window.relayClient.transaction(ctx => ctx.proteusDecryptSafe('alice', new Uint8Array(bytes)))), envelope);
  }
  assert.equal(await receive(newer), 'newer');
  assert.equal(await receive(older), 'older');
  await assert.rejects(receive(newer), 'a replay must never be rendered as a new message');
  const afterReplay = await alice.evaluate(async () => Array.from(await window.relayClient.transaction(ctx => ctx.proteusEncrypt('bob', new TextEncoder().encode('after replay')))));
  assert.equal(await receive(afterReplay), 'after replay');

  // Simulate a crash after the ratchet commits but before an outbox write.
  const stranded = await alice.evaluate(async () => Array.from(await window.relayClient.transaction(ctx => ctx.proteusEncrypt('bob', new TextEncoder().encode('stranded message')))));
  await alice.close();
  alice = await aliceContext.newPage();
  await startClient(alice, 'alice');
  const replacement = await alice.evaluate(async () => Array.from(await window.relayClient.transaction(ctx => ctx.proteusEncrypt('bob', new TextEncoder().encode('stranded message')))));
  assert.notDeepEqual(replacement, stranded, 're-encrypting after a crash must not be mistaken for the original ciphertext');
  assert.equal(await receive(stranded), 'stranded message');
  assert.equal(await receive(replacement), 'stranded message');

  console.log(JSON.stringify({ success: true, browserContexts: 2, recoveredAfterTabRestart: true, outOfOrder: true, replayRejected: true, sessionRecoveredAfterReplay: true, crashWindowChangesCiphertext: true, wasmOnlyCspException: true, initialCiphertextBytes: initial.length, replyCiphertextBytes: reply.length }));
} finally {
  await browser?.close();
  await new Promise(resolve => server.close(resolve));
}
