#!/usr/bin/env python3
"""Generate the synchronous browser directory from the canonical DAO inventory."""
import argparse, json, re
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
def generate():
    data = json.loads((ROOT / 'data/dao-directory.json').read_text())
    rows = data['daos']
    assert len({r['id'] for r in rows}) == len(rows)
    assert len({r['directoryName'] for r in rows}) == len(rows)
    organizations=data['organizations']
    assert len({o['id'] for o in organizations}) == len(organizations)
    for organization in organizations:
        units=[row for row in rows if row.get('organizationId') == organization['id']]
        assert any(row['id'] == organization['mainDaoId'] and bool(row['unitName']) for row in units)
        assert all(row['chainId'] == organization['chainId'] for row in units)
        assert len({row['unitName'].lower() for row in units}) == len(units)
    for row in rows:
        assert any(o['id'] == row['organizationId'] for o in organizations)
        if row.get('parentDaoId'):
            assert row['parentRelationship'] == 'organizational'
            assert any(p['id'] == row['parentDaoId'] and p['organizationId'] == row['organizationId'] for p in rows)
    sources=[r['membershipSource'] for r in rows if r.get('membershipSource')]
    assert len({s['file'] for s in sources})==len(sources), 'Membership files must be DAO-specific'
    for source in sources:
        assert re.fullmatch(r'[a-z0-9-]+\.json',source['file']), 'Invalid membership file'
        assert source['adapter'] in ('cw20-staked-legacy','cw4-group','native-staking'), 'Unsupported membership adapter'
        assert type(source['decimals']) is int and 0<=source['decimals']<=18
        assert source['unit'] and source['label']
    for row in rows:
        config = row.get('accountingSource')
        if not config: continue
        assert re.fullmatch(r'[a-z0-9-]+\.json', config['file'])
        assert config['adapter'] in ('nns-receipts', 'treasury-receipts', 'native-community-pool')
        assert config['scope'] and config['treasuries']
        assert len({(t['chain_id'], t['address']) for t in config['treasuries']}) == len(config['treasuries'])
        if row['core']: assert {'chain_id': row['network'], 'address': row['core']} in config['treasuries']
    return '// Generated by scripts/build_dao_directory.py; edit data/dao-directory.json.\nwindow.NetaDaoDirectory = Object.freeze(' + json.dumps(rows, ensure_ascii=True, separators=(',', ':')) + '.map(Object.freeze));\nwindow.NetaDaoOrganizations = Object.freeze(' + json.dumps(organizations, separators=(',', ':')) + '.map(Object.freeze));\n'
if __name__ == '__main__':
    parser = argparse.ArgumentParser(); parser.add_argument('--check', action='store_true'); args = parser.parse_args()
    path = ROOT / 'dao-directory.js'; output = generate()
    if args.check:
        if path.read_text() != output: raise SystemExit('Regenerate dao-directory.js')
    else: path.write_text(output)
