#!/usr/bin/env python3
"""Generate the synchronous browser directory from the canonical DAO inventory."""
import argparse, json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
def generate():
    data = json.loads((ROOT / 'data/dao-directory.json').read_text())
    rows = data['daos']
    assert len({r['id'] for r in rows}) == len(rows)
    assert len({r['directoryName'] for r in rows}) == len(rows)
    return '// Generated by scripts/build_dao_directory.py; edit data/dao-directory.json.\nwindow.NetaDaoDirectory = Object.freeze(' + json.dumps(rows, ensure_ascii=True, separators=(',', ':')) + '.map(Object.freeze));\n'
if __name__ == '__main__':
    parser = argparse.ArgumentParser(); parser.add_argument('--check', action='store_true'); args = parser.parse_args()
    path = ROOT / 'dao-directory.js'; output = generate()
    if args.check:
        if path.read_text() != output: raise SystemExit('Regenerate dao-directory.js')
    else: path.write_text(output)
